### ISSUE TITLE
Unable to capture onClick events on Marker's children included in deck.gl@^7.1.10

### ISSUE THREAD

**Issue by kfragkedaki** [uber/deck.gl#3389] opened 2019-07-30 13:06 UTC
#### Description
I used deck.gl@^6.4.7 and react-map-gl@^5.0.7, and I had placed a Marker with an icon children that was listening on click events. When I updated the deck.gl to version 7.1.10, the icon's click events stopped working.

#### Repro Steps
https://stackoverflow.com/questions/57222969/unable-to-capture-onclick-events-on-markers-children-included-in-deck-gl7-1-1

#### Environment:
 - Framework Version: deck.gl 7.1.10
 - Browser Version: Chrome 75.0
 - OS: Mac OS 10.14.5

**Comment by 1chandu** [comment] 2019-08-05 16:20
@kfragkedaki , could be related to this: https://github.com/uber/deck.gl/blob/master/docs/upgrade-guide.md#deck-class

**Comment by kfragkedaki** [comment] 2019-08-06 07:43
Hello @1chandu  , I don't have any problems with layer's click events. Controversially, on react-map-gl' s Marker and its children, onClick or onLayerClick does not work while it used to on previous versions of deck.gl.

```
<DeckGL
          initialViewState={{
            longitude: liveMapZoom.lng,
            latitude: liveMapZoom.lat,
            zoom: 12,
            bearing: 0,
            pitch: 0
          }}
          viewState={viewState}
          onClick={(info, event) => {
            console.log("info", info);
            console.log("event", event);
          }}
          onViewStateChange={this._onViewStateChange}
          controller={{ type: MapController, dragRotate: false }}
          layers={[
            layerCars(data)
          ]}
        >
          <ReactMapGL
            mapStyle={"mapbox://styles/mapbox/streets-v9"}
            mapboxApiAccessToken={TOKEN}
          >
           <Marker
             key={key}
             latitude={coordinates[1]}
             longitude={coordinates[0]}
            >
              <img
                alt={name}
                src={iconUrl}
                onClick={event => {
                  console.log("hey");
                }}
              />
            </Marker>
          </ReactMapGL>
</DeckGL>
```

**Comment by 1chandu** [comment] 2019-08-07 00:30
What is `ReactMapGL`? is it a `StaticMap` or  `InteractiveMap` (default) ?

Seems to be an issue with combination of DeckGL and react-map-gl. CC @Pessimistress

**Comment by kfragkedaki** [comment] 2019-08-07 09:19
You are right, I am using the InteractiveMap of ReactMapGL.

**Comment by benvium** [comment] 2019-11-11 18:11
FWIW I've experienced this issue too (@deck.gl/react": "^7.3.5", "react-map-gl": "^5.1.2").  The same issue occurs on both StaticMap and InteractiveMap.

**Comment by Pessimistress** [comment] 2019-11-11 20:18
The map component is rendered behind the Deck canvas, therefore unable to receive any pointer events. You need to render the Marker as a direct child of DeckGL, together with the [contextProvider](https://deck.gl/#/documentation/submodule-api-reference/deckgl-react/deckgl?section=contextprovider-react-component-optional-) prop,

**Comment by nbuonin** [comment] 2019-11-19 18:01
@Pessimistress If you use the contextProvider prop with `InteractiveMap`, how do you pass `mapStyle` and `mapboxApiAccessToken` to the map component? I can't seem to find any docs for `MapContext` under `react-map-gl`.

**Comment by R-D-P** [comment] 2019-12-10 10:43
Any update on this @Pessimistress, the markers show up after I use the context provider however they are neither clickable or draggable.

**Comment by R-D-P** [comment] 2019-12-16 11:52
I upgraded deck.gl to version 8  beta 1, the marker can now be dragged, however the underlying map is not visible.

    "deck.gl": "^8.0.0-beta.1",
    "react-map-gl": "^5.1.3",

If I comment out deck.gl and just use the staticMap from React-map-gl, the map is displayed, but when I am using with with deck.gl it's not being displayed.

**Comment by Pessimistress** [comment] 2019-12-16 16:58
@R-D-P Could you share your code? I can't reproduce your issue with the deck.gl examples.

**Comment by R-D-P** [comment] 2019-12-16 17:32
`
<DeckGL
            ref={this.deckRef}
            ContextProvider={MapContext.Provider}
            useDevicePixels={false}
            viewState={viewState}
            onViewStateChange={this.onViewStateChange}
            controller={{
              type: MapController,
              dragRotate: false,
              doubleClickZoom: false,
            }}
            onClick={this.onLayerClick}
            layers={deckLayer}
          >
            <StaticMap 
              mapStyle={
                satellite
                  ? `mapbox://styles/mapbox/satellite-v9`
                  : `mapbox://styles/mapbox/streets-v9`
              } 
              mapboxApiAccessToken={Meteor.settings.public.mapbox.accessToken}
            />
            {checkLocation && centerOfPolygon && (
              <Marker
                style={{ zIndex: 1 }}
                latitude={
                  centerDrone && markerDragged
                    ? centerOfPolygon.geometry.coordinates[1]
                    : checkLocation[1]
                }
                longitude={
                  centerDrone && markerDragged
                    ? centerOfPolygon.geometry.coordinates[0]
                    : checkLocation[0]
                }
                offsetLeft={-20}
                offsetTop={-10}
                draggable
                onDragEnd={this.onMarkerDrag}
              >
                <img src="/drone.png" draggable="false" alt="Name" />
              </Marker>
            )}
            {isMarkerPresent && markerPosition && (
              <Marker
                latitude={markerPosition[1]}
                longitude={markerPosition[0]}
                offsetLeft={-20}
                offsetTop={-10}
                draggable
                onDragEnd={event => this.onMarkerDrag(event)}
              >
                <img src="/drone.png" draggable="false" alt="Name" />
              </Marker>
            )}
          </DeckGL>

`

**Comment by R-D-P** [comment] 2019-12-16 17:34
excuse the two images, they're showing up in place of the closing marker tags for some reason.

**Comment by R-D-P** [comment] 2019-12-17 10:15
Update: I tried with deck.gl  7.3.9 and even in that the marker is not clickable or draggable.

**Comment by Pessimistress** [comment] 2019-12-18 00:34
@R-D-P do you mind give 8.0.0-beta.2 a try?

**Comment by R-D-P** [comment] 2019-12-18 08:12
@Pessimistress, I did give 8.0.0-beta2 a try as well..
The same as beta-1, the underlying map is not visible..
I saw two errors though that maybe helpful.

/node_modules/@deck.gl/layers/dist/es5/geojson-layer/geojson-layer.js:100 deck: `getLineDashArray` has been removed. Use `PathStyleExtension` instead

initializeState @ /node_modules/@deck.gl/layers/dist/es5/geojson-layer/geojson-layer.js:100
/node_modules/@deck.gl/layers/dist/es5/path-layer/path-layer.js:173 deck: `getDashArray` has been removed. Use `PathStyleExtension` instead

**Comment by kylebarron** [comment] 2020-01-04 00:37
I had a similar issue, but with `Source` and `Layer` instead of `Marker`. I was eventually able to figure it out by passing Deck.gl's click event to React Map GL's `queryRenderedFeatures`. See #4093 for an example. Presumably this would work on a `Marker` as well, but I haven't tested it.

**Comment by Pessimistress** [comment] 2020-01-05 00:34
Update: This issue is not going to be fixed for v7.x because it requires a breaking change. `deck.gl@8.0.0` allows all child elements to listen to pointer events, not just the deck canvas.

@R-D-P A bug fix made after beta.2 might make your base map visible again.

@kylebarron `Source` and `Layer` do not render DOM elements and they don't accept `onClick` events. Passing deck's click event to `queryRenderedFeatures` is the way to go.

**Closed** 2020-01-05 00:35 UTC
Labels: bug
