### ISSUE TITLE
heatmap layer shows only one color from colorRange

### ISSUE THREAD

**Issue by UttamRahane** [uber/deck.gl#3554] opened 2019-09-10 07:00 UTC
#### Repro Steps
const heatMap_layer = new HeatmapLayer({
                data: this.geoJson.features,
                id: 'heatmp-layer',
                opacity: 0.6,
                getPosition: d => d.geometry.coordinates,
                getWeight: d => d.properties['Max Capacity'],
               colorFormat: 'RGBA',
                colorRange: [[1, 152, 189, 255], [73, 227, 206, 255], [216, 254, 181, 255], [254, 237, 177, 255],[254, 173, 84, 255],[209, 55, 78, 255]],
                intensity: 1,
                radiusPixels: 80,
                threshold: 0.9
            });

 -->

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 7.2.3]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]

**Comment by 1chandu** [comment] 2019-09-10 16:10
Can you share result image? Which of the colors in colorRange are used? Also try adjusting `radiusPixels` and using default `colorRange`.

**Comment by UttamRahane** [comment] 2019-09-11 10:36
![image](https://user-images.githubusercontent.com/21005702/64690401-ecdf5200-d4ad-11e9-842c-a9c2cae0e0fe.png)

**Comment by UttamRahane** [comment] 2019-09-11 10:43
expected result should be something like -
![image](https://user-images.githubusercontent.com/21005702/64690866-0f259f80-d4af-11e9-8ad5-dd46b50daa0e.png)

**Comment by UttamRahane** [comment] 2019-09-11 10:44
expected result should be something like -

![image](https://user-images.githubusercontent.com/21005702/64690929-37150300-d4af-11e9-9f8a-907b436d928e.png)

**Comment by UttamRahane** [comment] 2019-09-11 10:57
using default colorRange, it shows only yellow color. that means it shows only first color.

**Comment by 1chandu** [comment] 2019-09-18 18:09
Based on your image it seems all the pixels are falling into lower end of heat map range. Locally I am not able to reproduce this problem, can you share your system details? Browser, GPU, OS (complete the environment section in description) ?  Also can you minimize the issue to few data samples and share that data here?

**Comment by SterlingMcCall** [comment] 2019-09-18 18:57
I am seeing this same issue with deck.gl v7.2.3 in Windows. It happens in both Chrome and Edge. It works as expected in Chrome on linux.

**Comment by UttamRahane** [comment] 2019-09-19 05:23
Browser : Chrome Version 76.0.3809.132
GPU: Intel(R) UHD Graphics 620
OS: windows 10
I'm trying to implement it using Vue
you can use geojson format and take value from properties

**Comment by SterlingMcCall** [comment] 2019-09-23 14:49
This bug occurs on Windows when hardware acceleration is enabled regardless of graphics chipsets. I tested both Nvidia and Intel graphics in Chrome and Edge 18 (non-chromium Edge). To prove the issue, go to chrome://settings/system and disable the option titled "Use hardware acceleration when available" and the heatmap will behave normally.

Issue still present as of deck.gl@7.2.6.

I do not know if this is a Chrome bug or a deck.gl bug, but it is definitely a bug.

**Comment by SterlingMcCall** [comment] 2019-09-23 14:58
To reproduce this bug, just look at the [heatmap demo in the documentation](https://deck.gl/#/documentation/deckgl-api-reference/layers/heatmap-layer) on a Windows machine with hardware acceleration enabled.

**Comment by tsherif** [comment] 2019-09-23 16:33
@UttamRahane @SterlingMcCall can you load up this page on your systems and let us know the results: https://tsherif.github.io/webgl2-render-target-test/

It should look like this: 
![Screen Shot 2019-09-23 at 12 32 52 PM](https://user-images.githubusercontent.com/476017/65444578-52acd180-ddfe-11e9-961a-33b9180e0b96.png)

**Comment by UttamRahane** [comment] 2019-09-23 17:09
The document page on chrome browser looks like:
![image](https://user-images.githubusercontent.com/21005702/65446683-80bc0100-de52-11e9-9863-c77f38cc8f10.png)
On Edge:
![image](https://user-images.githubusercontent.com/21005702/65446712-90d3e080-de52-11e9-8888-adfbcb8a3646.png)
@tsherif your page gives the same output as you expect but on chrome.
On Edge it gives a message 

> This example requires WebGL 2 which is unavailable on this system.

**Comment by SterlingMcCall** [comment] 2019-09-23 17:42
@UttamRahane @tsherif I misspoke about Edge. As would be expected, Edge does not work at all due to lack of WebGL2 support. I tried firefox on windows and observe the same issue with the same color everywhere, but disabling hardware acceleration in the firefox settings did not fix the issue like it did in Chrome.

@tsherif
Testing https://tsherif.github.io/webgl2-render-target-test/ on a Windows 10 machine with Intel HD graphics:

- Firefox with hardware acceleration - same as your screenshot
- Firefox without hardware acceleration - same as your screenshot
- Chrome with hardware acceleration - same as your screenshot
- Chrome without hardware acceleration
    - red, black, black, black
    - red, red, red, red
    - red, red, red, red
- Edge 18 - "This example requires WebGL 2 which is unavailable on this system."

**Comment by SterlingMcCall** [comment] 2019-09-23 17:52
On the same windows 10 machine with Intel HD graphics on Edge 18 with **deck.gl@7.3.0-beta.4** the heatmap displays this same visual issue seen on Chrome and Firefox.

**Comment by 1chandu** [comment] 2019-09-23 18:22
@SterlingMcCall , to summarize, when using `deck.gl@7.3.0-beta.4`,  it is specific Windows only, and happens on all browsers (Edge, Chrome and Firefox) ?   Also the issue is, it shows first color only from the `colorRange`  and there are no crashes in console?

**Comment by SterlingMcCall** [comment] 2019-09-23 19:17
@1chandu

>  to summarize, when using `deck.gl@7.3.0-beta.4`, it is specific Windows only, and happens on all browsers (Edge, Chrome and Firefox) ? Also the issue is, it shows first color only from the `colorRange` and there are no crashes in console?

Correct. That would be an mostly accurate summary. I would add the following:

- WebGL 1.0 support was added in `deck.gl@7.3.0-beta.4` allowing the bug to be seen in Edge, but previous versions of deck.gl also experience the same bug on WebGL 2.0 browsers. This would seem to rule out differences between 1.0 and 2.0.
- Not only is the first color from the `colorRange` picked, the edges do not fade smoothly. The `threshold` property has no effect and does not soften around the edges as you would expect.
- On Chrome, disabling hardware acceleration fixes the issue. Disabling hardware acceleration in Firefox has no effect. I was not able to determine if it is possible to disable hardware acceleration in Edge.
- The bug is observed in Windows machines running either Intel HD or Nvidia graphics. I could not test on AMD hardware.

Could it be a Windows bug?

**Comment by 1chandu** [comment] 2019-09-23 19:29
@SterlingMcCall , thanks for the details.

We are also seeing a crash in iOS due to unsupported WebGL feature (render to float textures), I am working on a fix to fallback to unsigned byte textures (with low precession), given what you are seeing is not a crash but rendering artifact, that could be a different issue specific to windows browsers. I will take a look.

> On Chrome, disabling hardware acceleration fixes the issue. Disabling hardware acceleration in Firefox has no effect. I was not able to determine if it is possible to disable hardware acceleration in Edge.

disabling `hardware acceleration`, uses software rendering (doesn't use GPU), so not limited by WebGL extension support. Firefox's software rendering might have bugs.

**Comment by tsherif** [comment] 2019-09-25 12:59
@1chandu The bug indeed appears to be in ANGLE. The easiest way I found to test is in Firefox, go to about:config and set `disable-angle` to `true`. The heatmap layer rendered fine for me afterwards. I tried to disable ANGLE in Chrome as well, but the browser became unresponsive so I couldn't test. 

If we narrow down the issue, we can report a bug here: https://bugs.chromium.org/p/angleproject/issues/list

**Comment by 1chandu** [comment] 2019-09-25 16:34
@tsherif , awesome !! I will dig more into this ..

**Comment by 1chandu** [comment] 2019-09-25 20:51
@SterlingMcCall @UttamRahane 
Can you try using deck.gl `7.3.0-beta.6`, this includes few fixes for `WebGL1` support.
Also can you try following demos:
1. `maxWeightLog` :  https://codepen.io/1chandu1/pen/rNBRqRz  
   => in console I am logging max weight, please copy paste the log
2. `custom maxWeight`: https://codepen.io/1chandu1/pen/BaBbGxQ
  => use the `maxWeight` slider and see if you able to see full color spectrum instead of single color, provide screen shots for like when maxWeight is 100 and 900.

Thanks.

**Comment by SterlingMcCall** [comment] 2019-09-25 21:24
Switching to `deck.gl@7.3.0-beta.6` has no impact on any browser on windows. The bug is still present.

demo 1 console output:
```
util.js:329 This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
w @ util.js:329
r._detectMissingCSS @ map.js:1500
r._setupContainer @ map.js:1513
r @ map.js:358
_create @ dist.min.js:6
_initialize @ dist.min.js:6
l @ dist.min.js:6
o @ dist.min.js:11
(anonymous) @ pen.js:2
pen.js:36 maxWeight: 0,0,0,0
pen.js:36 maxWeight: 0,0,0,0
pen.js:36 maxWeight: 0,0,0,0
```

demo 2:

![codepen io_1chandu1_pen_BaBbGxQ (1)](https://user-images.githubusercontent.com/8882589/65640010-f50bb700-dfae-11e9-9dd2-5900c696ce1b.png)
![codepen io_1chandu1_pen_BaBbGxQ](https://user-images.githubusercontent.com/8882589/65640011-f50bb700-dfae-11e9-8d44-75bd213b3e1d.png)

It would seem that your custom heatmap layer fixes/bypasses the issue. Awesome work!

**Comment by 1chandu** [comment] 2019-09-25 21:47
@SterlingMcCall , thanks for the details, this isolates the issue domain calculation, digging into it ...

**Comment by 1chandu** [comment] 2019-09-26 23:52
Problem root caused to rendering to 1X1 textures, workaround (specification of custom domain) will be part of 7.3 release (ETA 09/27).

**Comment by SterlingMcCall** [comment] 2019-09-26 23:58
@1chandu Awesome! Has a related ticket been opened on the ANGLE repo?

**Comment by 1chandu** [comment] 2019-09-27 04:56
> @1chandu Awesome! Has a related ticket been opened on the ANGLE repo?

Yes, link : https://bugs.chromium.org/p/angleproject/issues/detail?id=3941

**Comment by 1chandu** [comment] 2019-09-28 08:42
@SterlingMcCall @UttamRahane , please try deck.gl  '7.3.0-beta.9 ', and when using windows, set colorDomain props to [0, maxValue], where `maxValue` is big enough to show all hot spots. For website demo we are using 30000 for maxValue. Once ANGLE issue fixed this value will be auto calculated.

**Comment by SterlingMcCall** [comment] 2019-09-30 21:09
@1chandu Because it was available, I used the 7.3.0 release not the beta. Specifying the colorDomain does fix the issue, however it is not practical for dynamic datasets. In my use case, the maximum density of the data is not known so I am not able to choose an upper domain that works 100% of the time. 

From my very basic understanding of the algorithm, you recursively decrease the size of a texture until you end up with a 1x1 texture meeting some criteria, correct? Would it be possible to simply add a parameter to instead stop the algorithm at a 2x2 texture in the mean time?

Regardless, this effort and current work around is much appreciated.

**Comment by 1chandu** [comment] 2019-10-01 04:29
`colorDomain` is not the solution, we added it more like a feature for use cases where you want to control the domain to color mapping.

>From my very basic understanding of the algorithm, you recursively decrease the size of a texture until you end up with a 1x1 texture meeting some criteria, correct? Would it be possible to simply add a parameter to instead stop the algorithm at a 2x2 texture in the mean time?

I am not rendering to decreasing sizes, instead directly render to 1X1.  I am hoping the ANGLE [issue](https://bugs.chromium.org/p/angleproject/issues/detail?id=3941) is resolved soon, and this shouldn't be a problem.

**Comment by SterlingMcCall** [comment] 2019-10-01 12:22
> I am hoping the ANGLE issue is resolved soon, and this shouldn't be a problem.

While I agree that would be the optimal solution, [over half of Edge users](https://reports.adduplex.com/#/r/2019-09) are on a versions of Windows over a year old, and since Edge versions are tied to the Windows build, it could be a year or two after the ANGLE bug is fixed before a majority of Edge users will be able to take advantage of the dynamic domain calculation.

Is there any way to implement a workaround? Or is this bug too inherent to the domain calculation to do it differently?

**Comment by 1chandu** [comment] 2019-10-02 16:57
Stay tuned, will update here soon...

**Comment by 1chandu** [comment] 2019-10-03 21:39
@SterlingMcCall , added workaround for ANGLE issue in deck.gl 7.3.2, please give it a try, you don't have to set `colorDomain`, max value will be auto calculated.

**Comment by SterlingMcCall** [comment] 2019-10-07 16:34
@1chandu The workaround appears to be working correctly. Thank you!

**Comment by 1chandu** [comment] 2019-10-07 17:47
Thanks for confirming, closing !!

**Closed by 1chandu** 2019-10-07 17:47 UTC
Labels: bug
