### ISSUE TITLE
Git Push test is failing arc-lnglat

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#1896] opened 2018-06-07 22:50 UTC
<img width="1102" alt="screen shot 2018-06-07 at 3 48 27 pm" src="https://user-images.githubusercontent.com/25012840/41130219-8cf22bb4-6a6a-11e8-86cb-fad5231f12b4.png">

#### Actual Result
Failing.

#### Expected Result
Expected to pass.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment] 2018-06-07 22:54
@1chandu This is on an intel GPU

**Comment by georgios-uber** [comment] 2018-06-07 22:55
> MacBook Pro (Retina, 15-inch, Mid 2015)
> Intel Iris Pro

**Comment by 1chandu** [comment] 2018-06-08 16:22
Problem reproduced on `Intel Iris Pro` GPU, looking ...

**Comment by ibgreen** [comment] 2018-06-11 18:35
Close as duplicate of #1902

**Closed by ibgreen** 2018-06-11 18:35 UTC
Labels: bug, regression
