### ISSUE TITLE
Geo-located data drifts when resizing window at max zoom

### ISSUE THREAD

**Issue by JorinRBM** [uber/deck.gl#1306] opened 2018-01-09 01:56 UTC
If you navigate to this url: https://uber.github.io/deck.gl/#/documentation/layer-catalog/arc-layer in a non-maxed out chrome window, you can make the points drift by zooming out all the way, then dragging the window larger vertically.

This same effect can be seen when you have an implementation of geo-located data in your own project, so it seems there is a bug in updating the zoom of the data positions along with the zoom of the underlying map as the resize occurs.

**Comment by 1chandu** [comment] 2018-01-10 18:11
Thanks, I can reproduce the problem, I am looking into it.

**Comment by 1chandu** [comment] 2018-01-10 18:39
CC @Pessimistress @ibgreen 

At max zoom out level, when the height of the window is increased, deck.gl and mapbox viewport seem to get out of sync, it gets synced as soon as zoom level is increased. And this behavior is seen only when increasing the height of the window, not when decrease the height or increasing/decreasing the window width.  Also happens on 4.1-release, so not a new issue.

**Comment by Pessimistress** [comment] 2018-01-10 19:54
The viewport props is controlled by ReactMap rather than DeckGL. This should be filed as a bug on react-map-gl.

**Comment by ibgreen** [comment] 2018-01-23 23:09
Closing here since tracked in react-map-gl

**Closed by ibgreen** 2018-01-23 23:09 UTC
Labels: P2
