### ISSUE TITLE
add coordinate transformation api

### ISSUE THREAD

**Issue by dytmh** [uber/deck.gl#1390] opened 2018-02-05 01:43 UTC
can add coordinate transformation api ?

(lng,lat) to client screen(x,y)

**Comment by dytmh** [comment] 2018-02-05 03:31
i`m use mapbox api unproject and project have offset.

**Comment by ibgreen** [comment] 2018-02-05 04:43
Duplicate of #894

**Comment by Pessimistress** [comment] 2018-02-06 18:11
@dytmh Try this:
```js
import {WebMercatorViewport} from 'deck.gl';

const xy = new WebMercatorViewport(viewportProps).project(lngLat);
```

**Closed** 2018-02-09 23:07 UTC
Labels: Feature, duplicate
