### ISSUE TITLE
geojson layers

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#118] opened 2016-10-19 19:07 UTC
I know there was a ticket for this before, not sure where it went.

Two possible solutions as I see it:
1. Change all layers to accept GeoJSON as data
   - Choropleth already accepts geojson
   - Line -> FeatureCollection of LineString geometries
   - Arc -> FeatureCollection of LineString geometries that have two coordinate pairs (start/end)
   - ScatterPlot -> FeatureCollection of Point geometries
   - All options can be:
     - Passed into the constructor
     - On the FeatureCollection `properties` attribute
     - On each individual Feature `properties` attribute
2. Create a new layer that accepts a FeatureCollection full of any GeoJSON primitive, then transforms the data and picks the appropriate layers
   - All options can be:
     - Passed into the constructor prefixed with geometry type (`lineWidth` / `arcWidth` / `pointRadius` / `choroplethOpacity`)
     - On the FeatureCollection `properties` attribute
     - On each individual Feature `properties` attribute

Thoughts? I can take a swing at this once I know which direction to run in.

Personally leaning towards option 2 as its a lot easier from the user's perspective - toss arbitrary geojson into a layer and it just works. Could also do both!

**Comment by ibgreen** [comment] 2016-10-19 20:28
@contra - Yes we absolutely want a `GeoJsonLayer` that can accept GeoJson, and I do think you could help here.

I am currently working on a PR that will enable composite layers. There will be a new lifecycle method `renderSublayers` - in which a layer can create a list of new layers. I think this is what you would need for your proposal 2, which is the one I prefer.

This would enable us create a GeoJsonLayer that does not draw on its own, but instead renders a ChoroplethLayer, a LineLayer and a PointCloudLayer or ScatterplotLayer, to handle 'Polygons', 'Lines' and 'Points' geometries, respectively.

I'll try to post the branch today so you can see where this is heading, and if you like the approach, maybe you can take over and finish some of the details of implementing the GeoJSON spec?

In a sense you have already started the work - by thinking about the interface (props) we want the new layer to offer.

**Comment by ibgreen** [comment] 2016-10-20 00:09
@contra - a very raw GeoJsonLayer skeleton is up on https://github.com/uber/deck.gl/blob/lifecycle/src/layers/samples/geojson-layer/geojson-layer.js

This is on the lifecycle branch which I am still stabilizing so it might be premature to try to run anything. But at least you can look at the code and get an idea.

**Comment by ibgreen** [comment] 2016-10-20 03:58
Working GeoJsonLayer skeleton up on lifecycle branch - plenty of details left that need attention.

<img width="1009" alt="screen shot 2016-10-19 at 8 57 10 pm" src="https://cloud.githubusercontent.com/assets/7025232/19545861/ce909fda-963e-11e6-9db7-4c6d2a3ef6e4.png">

**Comment by ibgreen** [comment] 2016-12-01 05:11
Duplicate of #203

**Closed by ibgreen** 2016-12-01 05:11 UTC
