### ISSUE TITLE
plot example is broken on master

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#1150] opened 2017-11-14 19:27 UTC
as of commit 43e1333

@1chandu

**Comment by 1chandu** [comment] 2017-11-14 19:59
@ibgreen @shaojingli 
I regressed it and it is actually caused by :

> c66b9fefa3bcdf51c231c90fdf0a88e194dc510d is the first bad commit
> commit c66b9fefa3bcdf51c231c90fdf0a88e194dc510d
> Author: Ib Green <ibgreen@users.noreply.github.com>
> Date:   Fri Oct 27 13:41:57 2017 -0700
>     4.2-dev: Unified changeFlags handling (#1095)
> 
> :040000 040000 e941b202013621a1e1d66079f22919dfc6a2af35 1694156c09122ffcddd896a2ab88ad2b1b760480 M	src
> :040000 040000 e1379bebd7b314fc1b470097e79fe471a53bab39 16959808cf898ceec2f354177ee88cd373cbbea2 M	test
>

**Comment by 1chandu** [comment] 2017-11-14 21:05
Over to @ibgreen

**Comment by shaojingli** [comment] 2017-11-14 21:30
@ibgreen did #1149 solve this?

**Comment by jianhuang01** [comment] 2017-11-16 18:57
Fixed in #1160

**Closed by jianhuang01** 2017-11-16 18:57 UTC
