### ISSUE TITLE
This does not show properly on your website or when installing the repo. <deck.gl/examples/website/geojson/>

### ISSUE THREAD

**Issue by tkayne23** [uber/deck.gl#3927] opened 2019-11-25 02:26 UTC
This is what shows up on the website as an example.

![geojson](https://user-images.githubusercontent.com/4730833/69507482-5214e200-0ef8-11ea-86fb-14baa28a46e1.png)
![alt text](Isolated.png "Geojson")

**Comment by tsherif** [comment] 2019-11-25 15:47
Duplicate of #3886

**Closed by tsherif** 2019-11-25 15:47 UTC
Labels: bug
