### ISSUE TITLE
hexagon layer with height column

### ISSUE THREAD

**Issue by localdevjs** [uber/deck.gl#1852] opened 2018-05-23 16:23 UTC
I'm trying to get the hexagon layer/heatmap chart working with a height column. So my csv has 3 columns: lng,lat,height. Each lng/lat value will only occur once in the csv, but the height value is then used to determine how high to build that hex cell.

From what I understand, I should be looking at the "getElevationValue" function. But I'm not sure how to apply that function to my csv data? Is there a quick code example somewhere that demonstrates this?

Thanks in advance!

**Comment by danmarshall** [comment] 2018-05-23 17:34
In [this example](http://uber.github.io/deck.gl/#/examples/core-layers/hexagon-layer) they are using the `getPosition` function [here](https://github.com/uber/deck.gl/blob/5.2-release/examples/website/3d-heatmap/deckgl-overlay.js#L114). You would just add getElevationValue in the sample place.

**Comment by localdevjs** [comment] 2018-05-23 17:56
ok, but what is "d"? Is that a row in my csv? Is that some javascript object? How do I know what value to return in the getElevationValue? My question is that in the "getElevationValue", somehow I have to dig back into my csv and retrieve the height value for the current lat/lng pair.

**Comment by danmarshall** [comment] 2018-05-23 18:12
Yes it appears that each row in your csv will become an object. See https://github.com/uber/deck.gl/blob/5.2-release/examples/website/3d-heatmap/app.js#L30

The object should have property names which are the column titles in the csv.

**Comment by veikkoeeva** [comment] 2018-11-15 23:16
@danmarshall It looks like the problem is that the parameter is the points in the given bin and by default it returns the length of that bin. If that's the case, I don't see there is a way to set the height of the bar via explicit value. One option would be to preprocess the data.

I see there's a similar question at https://github.com/uber/deck.gl/issues/829, but I don't know how to proceed with that. Maybe @heshan0131 can kindly chime in? :)

I prepared some data at https://gist.githubusercontent.com/veikkoeeva/29cdb7e5cf9438a8e0181c9e5d8a99b8/raw/4640ef338dfd672e8e83228ff19003f7c27c0301/data.csv, just in case someone has the time to help here (it's data around China, Vietnam, Philippines).

**Comment by hijiangtao** [comment] 2018-12-27 09:34
@danmarshall I thought there's more than one modification that developers should concern about when they want to customize the elevation value via their own data，`getColorValue` is required at least since we change the display elevation of our map.

@veikkoeeva I think the problem you met can be resolved in this way.

Suppose your data is consists of many points, and you have property `SPACES` to defined the height you want to show:

```
[{
	COORDS: [lng, lat],
	SPACES: Math.random()*100,
	...
}, ...]
```

you can iterate the elevation input and take out the result from it in this way:

```
const getElevationValue = d => d.reduce(
	(accumulator, currentValue) => currentValue ? 
		accumulator + currentValue.SPACES : accumulator, 
	0
),
```

the input format can be found like this:

```
[
	{}, // YOUR ORIGINAL POINT
	{}, // YOUR ORIGINAL POINT
	...
	x: NUMBER,
	y: NUMBER,
]
```

the same approach can be applied in `getColorValue` method, for rendering the right color corresponding each hexagon with your customized height in `getElevationValue` method.

The issue #829 can be resolved by this way, too. Last, if your data not met the format of default data format, you should also define `getPosition` to get your project work well.

**Closed** 2019-01-02 22:45 UTC

**Comment by Ashirogi-Muto** [comment] 2020-12-11 04:56
I have been trying to achieve the same result where I have a weight property which I wanna use to give heights to the Hexagon cells.

`const layers = [
		new HexagonLayer({
			id: 'crowding-pattern',
			colorRange,
			coverage: 1,
			data,
			elevationRange: [0, 1000],
			elevationScale: 50,
			extruded: true,
			getPosition: d => {
				const { lat, lng } = d
				return [Number(lng), Number(lat)]
			},
			pickable: true,
			radius: 100,
			upperPercentile: 100,
			material,
			getElevationValue: d => {
				const { weight } = d[0]
				return weight
			},
			transitions: {
				getElevationValue: { duration: 800 }
			}
		})
	]`
I went through the whole issue and a couple more related to this but I am still not seeing any cells drawn!
Am I missing something?

**Comment by Ashirogi-Muto** [comment] 2020-12-11 05:36
I am trying to achieve the same result where I have property which I wanna use to define the height of the cells.

```const layers = [
		new HexagonLayer({
			id: 'crowding-pattern',
			colorRange,
			coverage: 1,
			data,
			elevationRange: [0, 1000],
			elevationScale: 50,
			extruded: true,
			getPosition: d => d.coordinates,
			pickable: true,
			radius: 20,
			upperPercentile: 100,
			material,
			getElevationValue: d => {
				const { weight } = d[0]
				return weight * 100
			},
			transitions: {
				getElevationValue: { duration: 800 }
			}
		})
	]```
But the cells that get drawn have no height! Am I missing something?
