### ISSUE TITLE
How to implement anti-aliasing for deck.gl layers

### ISSUE THREAD

**Issue by ilyabo** [uber/deck.gl#557] opened 2017-04-06 09:10 UTC
There is no anti-aliasing in deck.gl layers, so sometimes the appearance can be unpleasant:

![image](https://cloud.githubusercontent.com/assets/351828/24745460/1d26ceb6-1ab6-11e7-8357-c04bdd101804.png)

Apparently it isn't possible to just tell the browsers to enable anti-aliasing in WebGL. But it can be implemented in a fragment shader, like [this one](https://github.com/mattdesl/glsl-fxaa). But that particular shader requires rendering into a texture first which deck.gl doesn't do.

Another possibility would be to support artificially increasing devicePixelRatio in layers. This would probably have a significant negative impact on performance though.

Could you give any recommendation for implementing anti-aliasing and/or share your view on whether deck.gl should have some support for it?

Thanks in advance!

**Comment by shaojingli** [comment] 2017-04-06 18:57
@ilyabo thanks for your comments! Yeah, currently we don't do render to texture and post-processing. But this is one of the item on our list for next version! Stay tuned.

Right now, we suggest doing it by increasing the devicePixelRatio.

**Comment by shaojingli** [comment] 2017-09-19 16:49
close as duplicate of #573

**Closed** 2017-09-19 16:49 UTC
Labels: P2, v.Next
