### ISSUE TITLE
Deck.gl "under" raw mapbox layer z-index

### ISSUE THREAD

**Issue by cyrilchapon** [uber/deck.gl#2173] opened 2018-08-08 16:45 UTC
Hey,

I read about z contexts of deck.gl and mapbox.
In here we need some advanced visualizations, and are considering transitionning things from mapbox to deck.gl.

However, in the meantime of the transition, we need to overlay some deck.gl data in between multiple mapbox layers. Is that possible ?

**Comment by ibgreen** [comment] 2018-08-08 16:52
> we need to overlay some deck.gl data in between multiple mapbox layers. Is that possible ?

@cyrilchapon We are working on an integration with the new custom layer API that mapbox is developing #2132 . In the meantime, you'd need to work with two mapbox/react-map-gl instances. It is not very efficient, but as long as you not using 3D graphics (except in the top component, whether deck or mapbox) it could be made to work.

**Comment by ibgreen** [comment] 2018-08-08 16:52
Duplicate of #2132

**Closed by ibgreen** 2018-08-08 16:52 UTC

**Comment by Harrisandwich** [comment] 2018-11-07 15:00
@cyrilchapon Any luck with this? I'm currently in a similar situation where I would like to be able to show mapbox street and label layers over deck.gl layers. If you got this working and can provide an example it would be super helpful!

**Comment by cyrilchapon** [comment] 2018-11-07 17:56
Hey @Harrisandwich, sorry but I didn't fond anti solution so I went withtout deck.fl
