### ISSUE TITLE
Offset in Layer with Firefox ESR 52.x

### ISSUE THREAD

**Issue by mjrudnik** [uber/deck.gl#1216] opened 2017-12-05 16:02 UTC
Hello all together,

I have following setup:

![ff_specs](https://user-images.githubusercontent.com/18441053/33615471-8e4e87ee-d9da-11e7-972e-d6bb09ba0d5c.PNG)
![gpu](https://user-images.githubusercontent.com/18441053/33615472-8e677286-d9da-11e7-9732-a0de51545f28.PNG)
![windows_specs](https://user-images.githubusercontent.com/18441053/33615474-8e7df664-d9da-11e7-93bb-8b605d56a59f.PNG)

I get an huge Offset when rendering data on my map. But only when using Firefox ESR(version 52.2.0 32-bit).

In the following you can see which offset I'm talking about. All Lines should be on the streets.

FP64 (looks correct, but borders are a bit ragged)
![fp64](https://user-images.githubusercontent.com/18441053/33616597-9ebe10ec-d9dd-11e7-9d86-9bfce554bbe9.PNG)

FP32 (Offset + borders are ragged)
![fp32](https://user-images.githubusercontent.com/18441053/33616656-cabc6234-d9dd-11e7-9dc0-1efdc2c1faca.PNG)

**Comment by shaojingli** [comment] 2017-12-05 16:51
This is mostly probably due to Intel GPU's tangent problem. 

https://github.com/uber/deck.gl/pull/119

Somehow, under Firefox, the GPU model name is not properly reported, so the tan() workaround for Intel GPU is not activated.

The way to verify and fix it, is to check the GPU model string. @1chandu

**Comment by 1chandu** [comment] 2017-12-06 04:07
@mjrudnik , I verified on my macbook pro with Firefox 54 (not exactly your setup), I can see GPU model is correctly identified and Intel workarounds are properly applied.

Can you check on your console and see what type of renderer is created , here is the screen shot to help you :

<img width="1513" alt="screen shot 2017-12-05 at 7 59 43 pm" src="https://user-images.githubusercontent.com/9502731/33644075-9552e658-d9f7-11e7-83b9-8f76803c071a.png">

**Comment by mjrudnik** [comment] 2017-12-06 15:02
By filtering my console outups, i only get the following String: "luma.gl 3.0.0 - Assign luma.log.priority in console to control logging: 0: none, 1: minimal, 2: verbose, 3: attribute/uniforms, 4: gl logs
luma.log.break[], set to gl funcs, luma.log.profile[] set to model names"

There is no info about the WebGL Context Creation. 
What am i doing wrong?

**Comment by ibgreen** [comment] 2017-12-06 16:28
@mjrudnik Nothing. 

The driver identification depends on a WebGL extension [WEBGL_debug_renderer_info](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info). 

Your particular combination of browser and GPU driver (or possibly, security settings in the browser) most likely doesn't support this extension.

We'll need to do dynamic detection of this case. Until then we may just need to turn it on unconditionally.

**Comment by mjrudnik** [comment] 2017-12-06 16:37
> Until then we may just need to turn it on unconditionally.
@ibgreen What do you mean by that?

**Comment by ibgreen** [comment] 2017-12-06 16:41
Sorry, should have been clearer. 

We have a workaround for certain GPUs that don't provide enough precision in their built-in math functions. Since the workaround has a small performance impact, we only turn it on when we identify a GPU that exhibits the problem. But in a system such as yours, we don't get any information about the GPU, so we don't know. So at least in this case, we should opt to turn on the workaround.

**Comment by mjrudnik** [comment] 2017-12-06 16:44
> So at least in this case, we should opt to turn on the workaround.

@ibgreen How can this be done?

**Comment by ibgreen** [comment] 2017-12-06 16:57
We'll issue a patch asap.

**Comment by mjrudnik** [comment] 2017-12-06 17:25
Thank you for your help!

**Comment by 1chandu** [comment] 2017-12-07 01:21
@mjrudnik , following example creates GL context with debug information, this might show what the render string you are using, can you give it a shot and see what you have in console, it should be string like `luma.gl: luma.gl: Created WebGL2  ....`

example: http://uber.github.io/luma.gl/#/examples/core-examples/transform-feedback

**Comment by 1chandu** [comment] 2017-12-07 03:23
@mjrudnik , we just published new luma.gl patch `v4.0.6` that includes a potential fix for this problem : https://github.com/uber/luma.gl/releases

Can you re-install modules on your demo and test again, verify that luma.gl module version is `v4.0.6`.

**Comment by mjrudnik** [comment] 2017-12-07 08:26
@1chandu I opened your example and found following string in my console:
`luma.gl: luma.gl: Created WebGL2 debug context (Google Inc. ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0))`

**Comment by 1chandu** [comment] 2017-12-07 17:13
Thanks for checking that out, would be interesting to know the behavior of your demo with `v4.0.6` luma.gl patch.

**Comment by mjrudnik** [comment] 2017-12-08 13:22
@1chandu What's the correct way to install `v4.0.6` luma.gl? Usually is use npm to install my packages, but i think there is no extra release for your patch.

**Comment by 1chandu** [comment] 2017-12-08 15:43
@mjrudnik , we have published a new release for v4.0.6. If you remove your`node_modules` and any `yarn.lock` and do `npm install` you should get this release, you can verify using `npm ls luma.gl`

**Comment by mjrudnik** [comment] 2017-12-09 00:30
@1chandu I installed it the way you described, and by executing `npm ls luma.gl` I get the following:

├─┬ deck.gl@4.2.0-alpha.29
│ └── luma.gl@4.1.0-beta.1
├── luma.gl@4.0.6

But still I have the same problem as before.

**Comment by 1chandu** [comment] 2017-12-09 00:41
@mjrudnik , I see you are using the master branch of deck.gl (4.2.0) and luma.gl (4.1.0), this fix is not published in those yet. Is it possible for you to switch to latest release version of deck.gl (4.1.6),  when you install it should pickup luma.gl v4.0.6.

We have confirmed report from other users , that similar offset issue is resolved by luma.gl v4.0.6.

**Closed** 2017-12-09 00:50 UTC
Labels: bug

**Comment by ibgreen** [comment] 2017-12-09 00:53
> Is it possible for you to switch to latest release version of deck.gl (4.1.6), 

@1chandu That might not be possible if @mjrudnik is using new experimental features in deck.gl 4.2.0-alpha release. 

Suggest we publish luma.gl 4.1.0-beta.2 with the patch. 

I know that @georgios-uber also wants it.
