### ISSUE TITLE
DeckGL (Scripting) 5.3 doesn't fire onHover event for last frame

### ISSUE THREAD

**Issue by SinZ163** [uber/deck.gl#1882] opened 2018-06-03 15:50 UTC
In DeckGL (Scripting) v5.2, when listening to the onhover event on a pickable IconLayer, an event is fired when leaving the icon with `picked: false`, and `index: -1`

In 5.3 (Scripting), this is no longer the case.

In my gist linked below, (once you populate mapbox details) in deck5.2.html the popup appears and disappears. This isn't the case in deck5.3.html which uses the exact same code
#### Actual Result
Popup gets frozen
#### Expected Result
Popup gets removed
#### Reproduce Steps
Populate an IconLayer with data and set to `pickable: true`, register an event handler and listen to `picked` and `index` with the callback.
[Gist with reproduction](https://gist.github.com/SinZ163/e62fc6b8998bf4c22ec36ff4292cdf89)
[Codepen that can be forked with mapbox details and changed deckgl version in head](https://codepen.io/sinz163/pen/ERPKZb)

**Comment by Pessimistress** [comment] 2018-06-03 17:13
@ibgreen @georgios-uber this may be related to the deep picking refactor

**Comment by Pessimistress** [comment] 2018-06-04 18:30
Follow up:
https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/pick-layers.js#L95

`break` prevents empty picking results from triggering hover events.

**Comment by ibgreen** [comment] 2018-06-04 19:18
@Pessimistress Thanks, should be straightforward from here on. Assigning to @georgios-uber and myself.

**Comment by heshan0131** [comment] 2018-06-05 21:17
When will this be fixed? This is blocking kepler.gl upgrading to deck.gl v5. :)

**Comment by ibgreen** [comment] 2018-06-07 17:46
> When will this be fixed? 

Ambition is to get this fixed today and get a 5.3 patch release out this week.

**Comment by georgios-uber** [comment] 2018-06-07 20:52
Working on this... Will be done by today EOD.

**Comment by georgios-uber** [comment] 2018-06-07 21:01
@SinZ163 @heshan0131 When I run the layer browser example I cannot reproduce the issue.

**Comment by georgios-uber** [comment] 2018-06-07 21:10
OK, looks like `onLayerHover` of `<DeckGL />` is working fine.
Only `onHover` of layer is broken.

**Comment by georgios-uber** [comment] 2018-06-07 23:16
Fixed.

**Closed by georgios-uber** 2018-06-07 23:16 UTC
Labels: bug
