### ISSUE TITLE
deck.gl dependency strategy

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#269] opened 2016-12-20 19:42 UTC
Some users suggest that we establish a better strategy on deck.gl's dependency requirement and communicate it. Right now, luma.gl is a peer dependency of deck.gl that require user to install it themselves.

**Comment by ibgreen** [comment] 2016-12-20 21:34
Completely agree that it would be great to simplify the peer dependency situation. Just not sure how, Suggestions are most welcome.

The root cause is that npm is designed to install different versions of the same module, if two modules depend on it with incompatible semver versions.

For many utility type modules, simply installing two copies is a clever solution to mismatched dependencies. But in a library like luma.gl, luma objects are being created by the app and used as arguments to functions from luma.gl. Those objects must be created by the same version of the library or bad things can and will happen.

So, the reason that `luma.gl` is a peer dependency of `deck.gl` is that an application can only have one copy of `luma.gl`. For many apps this is not an issue, since they only install it through deck.gl, but some apps either use luma directly, or together with another module that uses luma or deck, and the app needs to ultimately decide which version everyone uses.

By the way, React has the same problem - All react components must install react as a peer dependency. Which seems to indicate that it is not a trivial problem to solve.

**Comment by ibgreen** [comment] 2017-01-09 03:47
All our major modules: luma.gl, deck.gl and react-map-gl are undergoing major reduction of npm dependencies for v3.0.0. Unfortunately it doesn't address the peer dependency problem, but it is still a major reduction to the cost of including these libraries into an app - installs will be faster, compiles and loads will be faster, and apps will be smaller.

Since I don't see a way of improving the peer dependencies themselves, I will close this for now. Will track it on the workboard.

**Comment by ibgreen** [comment] 2017-01-09 03:47
[Workboard](https://github.com/uber/deck.gl/projects/1)

**Closed by ibgreen** 2017-01-09 03:47 UTC

**Comment by donmccurdy** [comment] 2024-04-17 15:28
Sorry for raising a very old discussion, it seemed like the most relevant place. Some modules now have a fair number of peer dependencies. `@deck.gl/carto` is one example, with seven peer dependencies, [soon to be eight](https://github.com/visgl/deck.gl/pull/8703).

The division between dependencies and peerDependencies is not obvious to me, see the `@luma.gl/*` dependencies here:

https://github.com/visgl/deck.gl/blob/fa029dddebc43f350cef07cf8e9fe86d98415c02/modules/aggregation-layers/package.json#L40-L51

Each time a peer dependency is added, or its version incremented, that is technically a [breaking change under semver](https://github.com/semver/semver/issues/502). Whether it breaks users in practice would depend on whether the package in question was already somewhere in the dependency chain, which is hard to predict.

Perhaps a way to simplify this — while avoiding the "mismatched dependencies" risk — would be to take a policy that the relevant `*/core` module is always a peer dependency, while any other visgl-related modules are production dependencies, unless there's some particular reason for an exception? 

Because everything else depends on the `*/core` modules, I think that could be a way to minimize what end-users need to install, while also ensuring that compatible versions are used.
