### ISSUE TITLE
64-bit shader takes too long to compile

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#1126] opened 2017-11-07 23:15 UTC
I noticed in latest version, when enabling a polygon layer it takes too long, around 2-3 seconds.

Launched the example in examples/layer-browser. I noticed that the problem is the compilation of the shader and that it is much faster in version 4.0.0 (chosen as comparison).

<img width="835" alt="screen shot 2017-11-07 at 3 13 34 pm" src="https://user-images.githubusercontent.com/25012840/32523077-bde75cb4-c3ce-11e7-9930-2b15ebd90bf7.png">

I used the browser performance tool to measure when clicking fp64 in the demos.

> Chrome Version 58.0.3029.110 (64-bit)
> OSX El Capitan 10.11.6 (15G1217)
> MacBook Pro (Retina, 15-inch, Mid 2015)

I did bisect using git and found the following: (times are 32->64bit and 64->32 bit).

> Master: 2050 ms / 235 ms BAD
> Version 4.0.0: 1150 ms / 315 ms GOOD
> 
> 66004b29d8c8342e8a368f140e4820a24cb7feb7: 2500 ms / 334 ms BAD
> 719df3d57b6761235130aa263ad7ff89d28c58fb: SKIP
> 07f6a3ce4fef6534828e797a07de4cf783689382: SKIP
> 7b2045adeefcda9b1976769a5f95ae315ccb30ba: SKIP
> 9220eb619046e28bd3d7584d07effeb877f9bada: 1210 ms / 319 ms GOOD
> 80a6bd725a1c0e270938653e8f7177b0d2805306: 2080 ms / 240 ms BAD
> fc10a7c3e638ed943dcfb9e9eafb4d1d5ee0b4b3: 1010 ms / 207 ms GOOD
> 43212cebcca6560b98288ceecc1cacc76fa9b04e: 1050 ms / 212 ms GOOD
> 063a6e11eae0b7aaf0ad7e1ab8199fadb8ee3a77: 1950 ms / 242 ms BAD
> e458494e2c919ba903a7866275c9efa371c6ab13: 1970 ms / 209 ms BAD
> c958829658df0e1b8a388ca3f46d78428c41d4ad: 1050 ms / 221 ms GOOD
> a14eddf3e39558a439f480177487d64637049b66: 1930 ms / 202 ms BAD
> 
> FOUND : a14eddf3e39558a439f480177487d64637049b66

https://github.com/uber/deck.gl/commit/a14eddf3e39558a439f480177487d64637049b66

The problem is in src/core-layers/path-layer/path-layer-vertex-64.glsl.js

To reproduce:

1. Build and go to examples/layer-browser and start the browser (Chrome)
2. Enable Polygon layer / disable all others.
3. Inspect->Performance click record
4. Click fp64 in layer options.
5. Stop recording and look at the time (should be around 2-3 secs).
6. Edit path-layer-vertex-64.glsl.js and delete all code from main() lines 182-249
7. Repeat steps 1-5, notice new time.

**Comment by shaojingli** [comment] 2017-11-07 23:20
Is the time spent around compilation or link? It might be worthwhile to investigate while shader cache didn't function under this circumstance.

The commit is there for fixing the cracking issue of path layer when two segments are close to 180 degrees

**Comment by georgios-uber** [comment] 2017-11-07 23:28
@shaojingli :

- Check updated description with repro steps.
- If you revert the commit (has conflict because of path but you can hack it) the problem goes away.
- It happens on first draw() but I suspect that could be because of lazy initialization.

**Comment by 1chandu** [comment] 2017-11-07 23:33
@shaojingli @georgios-uber 
- I verified on the latest master using layer-browser + polygon layer, shaders are compiled only once (on first draw) and every draw after that (when toggling fp64 bit) we use the cached shaders (no compilation).

> It happens on first draw() but I suspect that could be because of lazy initialization.

So this regression only happens on first render, and when toggle off and on fp64, this problem doesn't occur? If so this could compile time.

**Comment by shaojingli** [comment] 2017-11-07 23:34
@georgios-uber any info on @1chandu 's question? does this occur every time when you turn on fp64? or it only happens once? If the former, we need to figure out why shader cache doesn't work.

@georgios-uber this commit cannot be reverted because 

> The commit is there for fixing the cracking issue of path layer when two segments are close to 180 degrees

**Comment by georgios-uber** [comment] 2017-11-08 00:15
@1chandu @shaojingli It happens every time, not just the first time.

**Comment by 1chandu** [comment] 2017-11-14 21:31
Resolved by :
https://github.com/uber/deck.gl/pull/1147
https://github.com/uber/luma.gl/pull/352

**Closed by 1chandu** 2017-11-14 21:31 UTC
Labels: bug, perf
