### ISSUE TITLE
how to handle the event of right-click

### ISSUE THREAD

**Issue by asling** [uber/deck.gl#1042] opened 2017-10-17 07:49 UTC
I have a new facility of right-click based on PathLayer of deck.gl in my project.  So how to do it?
Thanks all.

**Comment by 1chandu** [comment] 2017-10-17 18:13
@ibgreen @Pessimistress 

We are working on a new module 'mjolnir' (https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.0/break-out-event-manager-rfc.md) to handle all mouse events. If you are working on master branch you can give this a try.

**Comment by Pessimistress** [comment] 2017-10-17 21:38
@asling If you disable context menu on your app:
```
onContextMenu={event => event.preventDefault()}
```
`onClick` or `onClickLayer` callback should be fired on right click as well.

**Comment by 1chandu** [comment] 2017-10-20 16:57
@asling , closing, please re-open if the issue is still not resolved.

**Closed by 1chandu** 2017-10-20 16:57 UTC
