### ISSUE TITLE
example not show data vlaue

### ISSUE THREAD

**Issue by xuhande** [uber/deck.gl#601] opened 2017-04-27 09:48 UTC
hi, sir
  why I use  install of npm , can  see map ,but value not show data value. .

think you

**Comment by ibgreen** [comment] 2017-04-27 14:41
@xuhande Thanks for your feedback. We'll need a little more information to be able to help you. 

E.g. what sequence of npm commands are you using? npm install, npm start?

Are you trying to run deck.gl examples or writing your own app? etc.

**Comment by anmolgupta** [comment] 2017-04-27 16:06
Same issue with me. I am trying to make 3d-heatmap work using HexagonLayer. The data that I am providing to HexagonLayer is in the format [(position:[lon,lat]}...]. I have run npm install and then exported the variable, then npm start. it is not getting rendered. The problem is only with HexagonLayer. I have tried other layers as well which are working fine. Please suggest a solution  as soon as possible

**Comment by ibgreen** [comment] 2017-04-27 16:21
>  The problem is only with HexagonLayer. 

We do have an example for the `HexagonLayer` (`examples/3d-heatmap`). I just tested and noticed that it didn't run using `npm start` but did run using the `npm run start-local` script (which builds against the local source code instead of an installed version of deck.gl).

Looks like a bug that needs to be fixed asap, thanks for reporting it!

@heshan0131 @shaojingli

**Comment by shaojingli** [comment] 2017-04-27 17:50
This is simply because we forgot to include #590 to the 4.0-release branch

**Comment by shaojingli** [comment] 2017-04-27 18:23
Fixed in v4.0.6. Please update deck.gl installation and try again. Thanks

@xuhande @anmolgupta

**Closed by shaojingli** 2017-04-27 18:23 UTC
Labels: bug, v4.0
