### ISSUE TITLE
About gaps of the HexagonLayer

### ISSUE THREAD

**Issue by wlfei0502** [uber/deck.gl#4133] opened 2020-01-10 10:40 UTC
Hi，uber team:
       
       The gap of two hexagons is getting bigger and bigger when I keep moving map up. 
       I don't know how it causes.  
     
      Looking forward to reply.

        
![before move](https://user-images.githubusercontent.com/40889072/72146827-3eeea080-33d8-11ea-8333-016c775ef82e.png)

![after move](https://user-images.githubusercontent.com/40889072/72146939-72c9c600-33d8-11ea-89ad-60b9698f9fa8.png)

**Comment by 1chandu** [comment] 2020-01-10 18:28
Are you setting `coverage` prop? Can you copy paste what props are you setting. If you are setting coverage, this provides margin in pixels, this might looks narrower when you move away from it. I

**Comment by wlfei0502** [comment] 2020-01-13 01:30
Props is：

{
       id: 'hexagon-layer',
	visible:true,
	colorRange: color.colors,
	data,
	extruded:false,
	getPosition: d => {
		return d.geometry.coordinates;
	},
	radius:3000,
}

**Comment by Pessimistress** [comment] 2020-01-16 19:54
Duplicate of #4051

**Closed by Pessimistress** 2020-01-16 19:54 UTC
