### ISSUE TITLE
Unable to capture onDragEnd event on React-Map-Gl Marker  when used with deck.gl.

### ISSUE THREAD

**Issue by R-D-P** [uber/deck.gl#3811] opened 2019-10-28 15:10 UTC
When using deck.gl with React-Map-Gl, Markers added to react-map-gl are displayed under the deck.gl layers and maybe that is why they are not responding to onDrag events.

```
<DeckGL
            ref={this.deckRef}
            viewState={viewState}
            onViewStateChange={this.onViewStateChange}
            controller={{
              type: MapController,
              dragRotate: false,
              doubleClickZoom: false,
            }} 
            onClick={this.onLayerClick}
            layers={deckLayers}
          >
            <ReactMapGL
              mapStyle={
                satellite
                  ? `mapbox://styles/mapbox/satellite-v9`
                  : `mapbox://styles/mapbox/streets-v9`
              }
              mapboxApiAccessToken={Meteor.settings.public.mapbox.accessToken}
            >
              {geojson &&
                geojson.features.length > 0 &&
                geojson.features[0].geometry.coordinates.map(function(item, index) {
                  return (
                    <Marker
                      key={item}
                      latitude={item[1]}
                      longitude={item[0]}
                      offsetLeft={-8}
                      offsetTop={-18}
                      draggable
                      onDragEnd={event => newThis.onMarkerDrag(event, index)}
                    >
                      <div
                        style={{
                          width: 30,
                          height: 30,
                          borderRadius: 15,
                          backgroundColor: primaryColor,
                          display: 'flex',
                          justifyContent: 'center',
                          padding: 0,
                          zIndex: 1000,
                        }}
                      >
                        <RouteMarker index={index + 1} />
                      </div>
                    </Marker>
                  )
                })}
            </ReactMapGL>
          </DeckGL>
```

Environment  
-  deck.gl : ^7.1.10
 -  react-map-gl : ^5.0.7
 -  Chrome 78.0
 -  Mac OS X 10.15

**Comment by Pessimistress** [comment] 2019-10-29 23:22
@R-D-P the `ReactMap` component, when used as a child of `DeckGL`, is not interactive. You need to render the marker as a child of `DeckGL` along with the [contextProvider](https://deck.gl/#/documentation/submodule-api-reference/deckgl-react/deckgl?section=react-context) prop.

**Comment by R-D-P** [comment] 2019-11-13 08:15
Thanks for your response and sorry for mine being delayed, It works that way, however the react map gl marker is displayed below the deckgl layers and is not clickable or draggable. Any idea on how to grt it above the deckgl layers

**Comment by R-D-P** [comment] 2019-11-13 08:21
I set a high Z-index to the marker and it now shows above the deck.gl layers, however it is still not draggable.

**Comment by R-D-P** [comment] 2019-11-28 11:19
@Pessimistress  any Update?
 `<DeckGL
            ContextProvider={MapContext.Provider}
            ref={this.deckRef}
            viewState={viewState}
            onViewStateChange={this.onViewStateChange}
            controller={{
              type: MapController,
              dragRotate: false,
              doubleClickZoom: false,
            }}
            onClick={this.onLayerClick}
            layers={deckLayer}
            // onHover={info => this.onHover(info)}
          >
            <StaticMap
              // ContextProvider={MapContext.Provider}
              mapStyle={
                satellite
                  ? `mapbox://styles/mapbox/satellite-v9`
                  : `mapbox://styles/mapbox/streets-v9`
              }
              mapboxApiAccessToken={Meteor.settings.public.mapbox.accessToken}
              // containerStyle={this.props.containerStyle}
            />

            {checkLocation && centerOfPolygon && (
              <Marker
                style={{ zIndex: 9999 }}
                // ContextProvider={MapContext.Provider}
                latitude={
                  centerDrone && markerDragged
                    ? centerOfPolygon.geometry.coordinates[1]
                    : checkLocation[1]
                }
                longitude={
                  centerDrone && markerDragged
                    ? centerOfPolygon.geometry.coordinates[0]
                    : checkLocation[0]
                }
                offsetLeft={-20}
                offsetTop={-10}
                draggable 
                onDragEnd={event => this.onMarkerDrag(event)}
              >
                <img src="/drone.png" alt="Name" />
              </Marker>
            )}
             
          </DeckGL>`

This is my code, I am still not able to get the marker to be draggable, any help will be appreciated.

**Comment by Pessimistress** [comment] 2020-03-01 23:50
The child component activity issue is fixed in v8.

**Closed by Pessimistress** 2020-03-01 23:50 UTC
Labels: bug

**Comment by kulvinderkakarkk** [comment] 2022-08-08 06:44
I was facing the same issue. But the issue is related to the version number of the below packages in package.json file
"react-map-gl": "5.2.3",
"react-map-gl-geocoder": "2.0.11"

The following example works perfectly for the above packages
[https://codesandbox.io/s/l7p179qr6m](url)
