### ISSUE TITLE
IconLayer is broken on master branch.

### ISSUE THREAD

**Issue by jam-world** [uber/deck.gl#1278] opened 2017-12-25 06:25 UTC
I am trying to use the Iconlayer on master branch, however it seems broken. Everything works fine with the LineLayer. I installed only one copy of luma.gl that comes with the deck.gl@5.0.0.
```
const layer = new IconLayer();
...

<DeckGL {...viewport} layers={[layer]}></DeckGL>
```

Get error message:
```
luma.gl: `viewportSize` is no longer supported. Use `project_uViewportSize` instead,   check our Upgrade Guide for more details
luma.gl: `devicePixelRatio` is no longer supported. Use `project_uDevicePixelRatio` instead,   check our Upgrade Guide for more details
```

**Comment by shaojingli** [comment] 2018-01-02 12:54
@jam-world I don't see any issue when running the IconLayer example at `examples/icon`. Have you tried that?

**Comment by ibgreen** [comment] 2018-01-03 17:43
I can confirm that have seen these two warnings in an internal app that uses 5.0, both seem related to the IconLayer.

Strangely, searching the deck.gl code base I can only find a shader reference to `viewportSize` in the experimental `MultiIconLayer`. While that certainly needs to be fixed, it doesn't explain the reference to `devicePixelRatio`.

/Users/ib/Documents/deck.gl/docs/advanced/subclassed-layers.md:
```
  201: uniform vec2 viewportSize;
  ...
  210    // Find the center of the point and add the current vertex
  212:   vec2 vertex = positions.xy * instanceRadiusPixels / viewportSize * 2.0;
```

/Users/ib/Documents/deck.gl/src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex-64.glsl.js:
```
   41: uniform vec2 viewportSize;
```
/Users/ib/Documents/deck.gl/src/experimental-layers/src/text-layer/multi-icon-layer/multi-icon-layer-vertex.glsl.js:
```
   40: uniform vec2 viewportSize;
```
I believe @jianhuang01 is also looking at this.

**Comment by 1chandu** [comment] 2018-01-03 18:41
@jam-world , agree with @ib that `multi-icon-layer` should be fixed.

But IconLayer should work fine. You would see those error messages from luma.gl only if any of the shaders are using these removed uniforms. Are you using any custom shaders that use these uniforms? Please also double check deck.gl and luma.gl versions that got installed.

**Comment by ib** [comment] 2018-01-03 19:57
Hi, here is __ib__. Could you please use @ibgreen instead of @ib to address __ibgreen__, so that the right person will be notified. Thank you very much.

**Comment by jianhuang01** [comment] 2018-01-03 23:40
After debugging the icon example, I found the the 5.0.0 deck.gl we published, has two lines of commented code.
// uniform vec2 viewportSize;
// uniform float devicePixelRatio;

although the glsl code are commented, but still treated as valid code by our checking module and reported as errors. The latest code in master branch is good, we need publish a new version.

Before publishing new lib, I am going to fix the two valid bugs in multi-icon-layer.

**Comment by ibgreen** [comment] 2018-01-04 00:21
Great find. 
* Note that the multi-icon-layer is and experimental layer and published separately as part of deck.gl-layers. We do need to publish a v0.19 to fix our internal app.
* I think you can go ahead and cherry-pick the removal of the commented lines to 5.0-release branch and publish 5.0.1. Check with @1chandu

**Comment by 1chandu** [comment] 2018-01-04 02:49
Thanks @jianhuang01 
Looks like the change is in 5.0-release branch already but the published version doesn't include this, and another commit. Lets also merge #1277 and cherry-pick to 5.0-release before we do a patch release. We can also publish website after that.

**Comment by jianhuang01** [comment] 2018-01-05 00:08
Resolved in deck.gl@5.0.1

**Closed by jianhuang01** 2018-01-05 00:08 UTC
Labels: bug
