### ISSUE TITLE
Double head banner in deck.gl's website

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#670] opened 2017-05-31 04:43 UTC
When blog is clicked, I saw this 

<img width="1680" alt="screen shot 2017-05-30 at 9 40 55 pm" src="https://cloud.githubusercontent.com/assets/21322704/26616097/f410c9d2-4580-11e7-9e7b-396062a27bcb.png">

**Comment by Pessimistress** [comment] 2017-05-31 05:40
That would be another change we made on master instead of 4.0-release...

Xiaoji
_____________________________

**Comment by ibgreen** [comment] 2017-05-31 17:44
> That would be another change we made on master instead of 4.0-release...

How do we fix this? The demo is on` 4.0-release` and the blog is on the `blog` branch - do they still have a dependency on `master`? Is that the root cause that we should fix?

**Comment by Pessimistress** [comment] 2017-05-31 18:54
I have cherry-picked the missing commits into 4.0-release. The site should be fixed now.

**Closed by Pessimistress** 2017-05-31 18:54 UTC
