### ISSUE TITLE
Using Screen Grid Deck GL with Superset

### ISSUE THREAD

**Issue by alldoami** [uber/deck.gl#2109] opened 2018-07-20 22:45 UTC
Hello team! 

I am creating a Screen Grid Deck GL map of locations in Superset with specific weights assigned to them and want to show more information about them when I hover over them. Superset allows to edit the Javascript with these three boxes: 

![image](https://user-images.githubusercontent.com/16328889/43028281-dd15c9da-8c33-11e8-9327-94ad5bc9f62b.png)

How should I go about showing more info about the specific locations?

Thanks!

**Comment by alldoami** [comment] 2018-07-20 23:01
When entering this into the tooltip generator box (using one of the examples): 

d => {
    return `<strong>${d.object.extraProps.geohash} </strong>`
}

The geohash is shown on locations on the map that aren't spawned squares (out in the middle of the ocean for example).

**Comment by 1chandu** [comment] 2018-07-25 22:37
@alldoami 

duplicate of https://github.com/uber/deck.gl/issues/1880 ?

**Comment by alldoami** [comment] 2018-07-26 17:57
@1chandu yes

**Closed** 2018-07-26 17:57 UTC

**Comment by CarlosMgno** [comment] 2022-03-23 12:48
when trying to generate the deck.gl Screen Grid does not plot color on the map

![Captura de tela 2022-03-23 094716](https://user-images.githubusercontent.com/99760368/159702477-1c6f8058-0081-4733-80b6-4bcdbb677170.jpg)
